name: simplenv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.5.0=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - importlib_resources=6.1.1=py39h06a4308_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libllvm14=14.0.6=hdb19cb5_3
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=3.8.0=py39h06a4308_0
  - matplotlib-base=3.8.0=py39h1128e8f_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - pcre2=10.42=hebb0a14_0
  - pillow=10.2.0=py39h5eee18b_0
  - ply=3.11=py39h06a4308_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.3.3=py39h5eee18b_0
  - tzdata=2023d=h04d1e81_0
  - xz=5.4.5=h5eee18b_0
  - zipp=3.17.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - appdirs==1.4.4
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==2.0.0
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - gym==0.20.0
      - idna==3.6
      - jinja2==3.1.3
      - ma-gym==0.0.14
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - mypy==1.8.0
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python-headless==4.9.0.80
      - packaging==23.2
      - pip==23.0.1
      - protobuf==4.25.2
      - psutil==5.9.8
      - pyglet==1.5.27
      - pyqt5==5.14.2
      - pyyaml==6.0.1
      - requests==2.31.0
      - scipy==1.12.0
      - sentry-sdk==1.40.3
      - setproctitle==1.3.3
      - setuptools==66.0.0
      - smmap==5.0.1
      - sympy==1.12
      - tensordict==0.3.1
      - torch==2.2.1
      - torchrl==0.3.0
      - torchvision==0.17.1
      - tqdm==4.66.2
      - triton==2.2.0
      - typing-extensions==4.9.0
      - urllib3==2.2.0
      - wandb==0.16.3
      - wheel==0.38.4
prefix: /home/uosai/바탕화면/miniconda3/envs/simplenv
